name: Discord Sync

on:
  schedule:
    - cron: "0 5 * * *"   # chạy 12h trưa VN
    - cron: "0 17 * * *"  # chạy 12h đêm VN
  workflow_dispatch: # cho phép bấm chạy tay

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: node sync.js
        env:
          TOKEN: ${{ secrets.TOKEN }}
          GUILD_ID: ${{ secrets.GUILD_ID }}
          SHEET_API: ${{ secrets.SHEET_API }}
